# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nicholas Wolf
tagline:             'Software Developer'
description:         'Software Developer & Multimedia Artist.'
url:                 http://nicwolf.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nicholas Wolf
  email:             nicwolf1@gmail.com

# Custom vars
version:             1.0.0
